### PR TITLE
Rename bq_aquarise5 to the original device codename "vegetalte"

### PR DESCRIPTION
**Pull request by Herna1994**
It needs the repo name to be changed to android_device_bq_vegetalte

### CODE REVIEW

**Comment by Herna1994** [comment]
I think is better to use the codename provided by the original kernel source readme.md. Now I will send another pull request for a updated readme.md for the device tree

**Comment by Kra1o5** [comment]
Is a codename for kernel only.
So the correct way is to use the same name of stock roms.

**Comment by Herna1994** [comment]
Yeah, but well using a codename could be easier and better than aquarise5. It is true is the only one who has Qualcomm, but there are more aquarise5 devices, so I think it would be better to use the kernel codename for the device codename.

Like for example android_device_oneplus_bacon. This looks better than android_device_oneplus_one for example.

**Comment by Kra1o5** [comment]
Well, to be more standard.

On stock is named as:

ro.product.model=Aquaris E5
ro.product.device=Aquaris_E5

To identify it in the Play store & avoid problems with applications marked as incompatible.

**Comment by Herna1994** [comment]
The true is that I don´t have the device, so that´s why I did not know what is inside the build.prop. Just thought was easier to compile, since model and device in part can be assigned inside .mk

**Comment by Kra1o5** [comment]
I dont have it too.

Can use vegetalte as device identifier & use PRODUCT_BUILD_PROP_OVERRIDES to set the correct name for build.prop.

But PRODUCT_MODEL := Aquaris E5 4G is wrong, the correct is PRODUCT_MODEL := Aquaris E5

To avoid different model names.

**Comment by Herna1994** [comment]
Ah yes, well just said to make differences from normal E5 HD/FHD and then
4G one that comes with Qualcomm and all new stuff :D

2015-01-15 16:58 GMT+01:00 Kra1o5 notifications@github.com:

**Comment by Kra1o5** [comment]
Sure, if you change PRODUCT_MODEL := Aquaris E5 4G for PRODUCT_MODEL := Aquaris E5 
I merge it.

**Comment by Herna1994** [comment]
Okey, dame dos minutos :P

Btw, it is mentioned everywhere(kernel page, website...) as Aquaris E5 4G.
I don´t know what sense has to have it as Aquaris E5. The only place where
it appears like that is in the black box that comes with the phone, on the
rest, it is Aquaris E5 4G.

2015-01-15 17:02 GMT+01:00 Kra1o5 notifications@github.com:

**Comment by Kra1o5** [comment]
Yes, more intuitive to use 4G instead of Aquaris E5 without 4G but they called so we need to make the same.

**Comment by Herna1994** [comment]
Bueno Kratos, ahí lo llevas tal y como habías sugerido :)

**Comment by sooorajjj** [comment]
guys a little help over here pls
 https://github.com/YU-YUREKA/android_device_yu_tomato
trying to get twrp booting

**Comment by Herna1994** [comment]
Okey, moving to the organization. I will help if find time, but Kra1o5 is
much good in this.

2015-01-15 22:23 GMT+01:00 Sooraj notifications@github.com:

**Comment by sooorajjj** [comment]
@Herna1994 thank you so much 
looking forward to hear from you guys

sooraj

**Comment by Kra1o5** [comment]
Please use irc channel to get support here: #twrp

**Pull request merged**
